## Overview


1. Label Encoder

2. Categorical features

3.  Bin cut

4. Missing value

5.  Correlation

In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

## 1. Label encoding

- Easier case
- Assume traing and test data have same category

- Use F1, F2 for X 

- Format le.fit_transform(df['colname'])


#### Label Encoding for new testing label

- Method1: Extract all category
- Method2: remove row with new type (use in predict)

In [7]:
from sklearn.preprocessing import LabelEncoder

train_df = pd.read_csv('data/train1.csv')
class_le = LabelEncoder()
y = class_le.fit_transform(train_df['Class'])

print(y,'\n')

print('Inverse transform',list(class_le.inverse_transform(y)))


[0 1 2 3 1 2 0 3 1 0] 

Inverse transform ['c1', 'c2', 'c3', 'c4', 'c2', 'c3', 'c1', 'c4', 'c2', 'c1']


## 2. One Hot Encoding 

- Convert to labelencoding then do OneHotEncoding
- OneHotEncoding with unseen values
- pandas get_dummies
- Category Encoding



### 2-1.  Convert to LabelEncoding then do OneHotEncoding

In [46]:
### import training data

train_df_raw = pd.read_csv('data/train1.csv')
test_df_raw = pd.read_csv('data/test.csv') 

train_df_raw.head()

Class F1  F2  F3  F4
0    c1  r   L   1  N1
1    c2  g   X   3  N2
2    c3  b  XL   4  N1
3    c4  r   S   3  N3
4    c2  g   S   2  N5

In [47]:

### Sklearn version   >> 對F1, F2做 label encoding

train_df=train_df_raw.copy()
test_df=test_df_raw.copy()


F1_le = LabelEncoder()
F2_le = LabelEncoder()


train_df = train_df[['F1','F2']]

train_df['F1'] = F1_le.fit_transform(train_df['F1'])
train_df['F2']  = F2_le.fit_transform(train_df['F2'] )

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse = False)

ohe.fit_transform(train_df)

array([[0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0.]])

### 2-2.  OneHotEncoding with unseen values

- F4 is different in training and testing
- We can use handle_unknown='ignore' in one hot encoding

In [44]:
train_df=train_df_raw.copy()
test_df=test_df_raw.copy()


train_all_features = train_df[['F1','F2','F3','F4']].copy()
test_all_features = test_df[['F1','F2','F3','F4']].copy()


from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse = False,handle_unknown='ignore')

train_onehot=ohe.fit_transform(train_all_features)
test_onehot=ohe.fit_transform(test_all_features)

test_onehot

array([[0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.]])

### 2-3.  Pandas get_dummies

- Only convert categorical features
- Can Set prefix for column names
- When unseen values appear in test data

In [54]:
train_df=train_df_raw.copy()
test_df=test_df_raw.copy()

train_df_new = pd.get_dummies(train_df[['F1','F2','F3','F4']],prefix = ['color','size','N'])
train_df_new

F3  color_b  color_g  color_n  color_r  size_L  size_S  size_X  size_XL  \
0   1        0        0        0        1       1       0       0        0   
1   3        0        1        0        0       0       0       1        0   
2   4        1        0        0        0       0       0       0        1   
3   3        0        0        0        1       0       1       0        0   
4   2        0        1        0        0       0       1       0        0   
5   4        1        0        0        0       0       0       1        0   
6   6        0        0        1        0       0       1       0        0   
7   8        0        0        0        1       0       0       0        1   
8   9        0        0        0        1       0       0       0        1   
9   1        0        1        0        0       1       0       0        0   

   N_N1  N_N2  N_N3  N_N4  N_N5  
0     1     0     0     0     0  
1     0     1     0     0     0  
2     1     0     0     0     0  
3     0     0     1     0     0  
4     0     0     0     0     1  
5     1     0     0     0     0  
6     0     1     0     0     0  
7     0     0     0     1     0  
8     0     1     0     0     0  
9     1     0     0     0     0

In [66]:
### Deal with unseen features

train_df=train_df_raw.copy()
test_df=test_df_raw.copy()

train_df_x = train_df.drop(['Class'],axis = 1)
test_df_x = test_df.drop(['Class'],axis = 1)
onehot_training = pd.get_dummies(train_df_x)
onehot_testing = pd.get_dummies(test_df_x)

final_train,final_test = onehot_training.align(onehot_testing,
                                              join = 'left',
                                              axis = 1)
final_test

F3  F1_b  F1_g  F1_n  F1_r  F2_L  F2_S  F2_X  F2_XL  F4_N1  F4_N2  F4_N3  \
0   2     0     1   NaN     0     1     0     0      0      1      0      0   
1   4     0     0   NaN     1     0     0     1      0      1      0      0   
2   6     1     0   NaN     0     0     0     0      1      0      1      0   
3   8     1     0   NaN     0     0     1     0      0      0      1      0   
4   9     0     0   NaN     1     0     1     0      0      0      0      1   
5   1     0     1   NaN     0     0     0     1      0      0      0      0   
6   1     0     0   NaN     1     0     1     0      0      0      0      1   
7   3     0     1   NaN     0     0     0     0      1      0      0      0   
8   4     0     1   NaN     0     0     0     0      1      1      0      0   
9   3     1     0   NaN     0     1     0     0      0      0      0      0   

   F4_N4  F4_N5  
0    NaN      0  
1    NaN      0  
2    NaN      0  
3    NaN      0  
4    NaN      0  
5    NaN      1  
6    NaN      0  
7    NaN      1  
8    NaN      0  
9    NaN      0

### 2-4.  Categorical Encoding package

- Best one to use
- Convert onlt categorical features
- can deal with unseen features


#### reference: https://medium.com/hugo-ferreiras-blog/dealing-with-categorical-features-in-machine-learning-1bb70f07262d

In [74]:
import category_encoders as ce

train_df=train_df_raw[['F1','F2','F3','F4']].copy()
test_df=test_df_raw[['F1','F2','F3','F4']].copy()

ohe = ce.OneHotEncoder(handle_unknown = 'ignore',use_cat_names = True)
train_ohe = ohe.fit_transform(train_df)
train_ohe.head()

F1_r  F1_g  F1_b  F1_n  F2_L  F2_X  F2_XL  F2_S  F3  F4_N1  F4_N2  F4_N3  \
0     1     0     0     0     1     0      0     0   1      1      0      0   
1     0     1     0     0     0     1      0     0   3      0      1      0   
2     0     0     1     0     0     0      1     0   4      1      0      0   
3     1     0     0     0     0     0      0     1   3      0      0      1   
4     0     1     0     0     0     0      0     1   2      0      0      0   

   F4_N5  F4_N4  
0      0      0  
1      0      0  
2      0      0  
3      0      0  
4      1      0

In [75]:
test_ohe = ohe.transform(test_df)
test_ohe.head()

F1_r  F1_g  F1_b  F1_n  F2_L  F2_X  F2_XL  F2_S  F3  F4_N1  F4_N2  F4_N3  \
0     0     1     0     0     1     0      0     0   2    1.0    0.0    0.0   
1     1     0     0     0     0     1      0     0   4    1.0    0.0    0.0   
2     0     0     1     0     0     0      1     0   6    0.0    1.0    0.0   
3     0     0     1     0     0     0      0     1   8    0.0    1.0    0.0   
4     1     0     0     0     0     0      0     1   9    0.0    0.0    1.0   

   F4_N5  F4_N4  
0    0.0    0.0  
1    0.0    0.0  
2    0.0    0.0  
3    0.0    0.0  
4    0.0    0.0

## 3.資料處理 -- 標準化與資料切割

- Data description
- Train Test Split
- Standardize
- Normalize
- bin cut

In [103]:
### Read Datset  


df_wine = pd.read_csv('https://archive.ics.uci.edu/'
                      'ml/machine-learning-databases/wine/wine.data',
                      header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.describe()

Class labels [1 2 3]


Class label     Alcohol  Malic acid         Ash  Alcalinity of ash  \
count   178.000000  178.000000  178.000000  178.000000         178.000000   
mean      1.938202   13.000618    2.336348    2.366517          19.494944   
std       0.775035    0.811827    1.117146    0.274344           3.339564   
min       1.000000   11.030000    0.740000    1.360000          10.600000   
25%       1.000000   12.362500    1.602500    2.210000          17.200000   
50%       2.000000   13.050000    1.865000    2.360000          19.500000   
75%       3.000000   13.677500    3.082500    2.557500          21.500000   
max       3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total phenols  Flavanoids  Nonflavanoid phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280/OD315 of diluted wines      Proline  
count                    178.000000   178.000000  
mean                       2.611685   746.893258  
std                        0.709990   314.907474  
min                        1.270000   278.000000  
25%                        1.937500   500.500000  
50%                        2.780000   673.500000  
75%                        3.170000   985.000000  
max                        4.000000  1680.000000

In [104]:
### Train Test split

from sklearn.model_selection import train_test_split

x = df_wine.drop(['Class label'],axis = 1)
y = df_wine[['Class label']]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state = 0)


In [105]:
### Standardize

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

x_train_std

array([[ 0.87668336,  0.79842885,  0.64412971, ...,  0.0290166 ,
        -1.06412236, -0.2059076 ],
       [-0.36659076, -0.7581304 , -0.39779858, ...,  0.0290166 ,
        -0.73083231, -0.81704676],
       [-1.69689407, -0.34424759, -0.32337513, ...,  0.90197362,
         0.51900537, -1.31256499],
       ...,
       [-0.70227477, -0.68615078, -0.65828065, ...,  0.46549511,
         0.51900537, -1.31256499],
       [ 1.13777093, -0.62316862, -0.91876272, ..., -0.18922266,
         1.03282752,  0.80164614],
       [ 1.4610222 ,  0.12361993,  0.42085937, ..., -1.45501034,
        -1.2168803 , -0.2719767 ]])

In [106]:
### Normalizer

from sklearn.preprocessing import Normalizer
nl = Normalizer()
nl.fit(x_train)
x_train_std = nl.transform(x_train)
x_test_std = nl.transform(x_test)


x_train_std

array([[1.98740683e-02, 4.73261232e-03, 3.68737279e-03, ...,
        1.39365271e-03, 2.64213326e-03, 9.87170669e-01],
       [2.52769066e-02, 3.04757030e-03, 4.50163979e-03, ...,
        1.91220097e-03, 4.10326459e-03, 9.85978626e-01],
       [3.23359735e-02, 5.53774417e-03, 6.34475212e-03, ...,
        3.22803178e-03, 8.23704661e-03, 9.60061176e-01],
       ...,
       [3.42652179e-02, 4.44178750e-03, 6.04193455e-03, ...,
        2.92440668e-03, 8.16626770e-03, 9.51811607e-01],
       [1.40342669e-02, 1.69622794e-03, 2.14047811e-03, ...,
        9.18790134e-04, 3.36216609e-03, 9.94514595e-01],
       [2.12363700e-02, 3.76435655e-03, 3.71936424e-03, ...,
        9.29841059e-04, 2.56456163e-03, 9.89830805e-01]])

### Bin cut

1. create a new column by cutting target column
2. Find the cutting edge
3. split original column by cutting edge
4. drop new column
5. cut 可以自訂cutting age
  - bins = [18, 25, 35, 60, 100]
  - cats = pd.cut(ages, bins)

In [107]:
x_train_cut = x_train.copy()
x_test_cut = x_test.copy()

x_train_cut ['Alcohol_cut'] = pd.cut(x_train_cut ['Alcohol'],3)
print(np.unique(x_train_cut ['Alcohol_cut']))

full_data = (x_train_cut,x_test_cut)
for data in x_train_cut,x_test_cut:
    data.loc[data['Alcohol']<=12.27,'Alcohol']=0
    data.loc[(data['Alcohol']<=13.51) & (data['Alcohol']>12.27),'Alcohol'] = 1
    data.loc[data['Alcohol']>13.51,'Alcohol'] = 2
    
x_train_cut

[Interval(11.026, 12.27, closed='right')
 Interval(12.27, 13.51, closed='right')
 Interval(13.51, 14.75, closed='right')]


Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
161      2.0        3.26  2.54               20.0        107           1.83   
92       1.0        1.53  2.26               20.7         80           1.38   
94       0.0        1.99  2.28               18.0         98           3.02   
174      1.0        3.91  2.48               23.0        102           1.80   
24       1.0        1.81  2.61               20.0         96           2.53   
..       ...         ...   ...                ...        ...            ...   
103      0.0        1.72  1.88               19.5         86           2.50   
67       1.0        1.17  1.92               19.6         78           2.11   
117      1.0        1.61  2.19               22.5        108           2.00   
47       2.0        1.68  2.12               16.0        101           3.10   
172      2.0        2.51  2.48               20.0         91           1.68   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
161        0.56                  0.50             0.80             5.88  0.96   
92         1.46                  0.58             1.62             3.05  0.96   
94         2.26                  0.17             1.35             3.25  1.16   
174        0.75                  0.43             1.41             7.30  0.70   
24         2.61                  0.28             1.66             3.52  1.12   
..          ...                   ...              ...              ...   ...   
103        1.64                  0.37             1.42             2.06  0.94   
67         2.00                  0.27             1.04             4.68  1.12   
117        2.09                  0.34             1.61             2.06  1.06   
47         3.39                  0.21             2.14             6.10  0.91   
172        0.70                  0.44             1.24             9.70  0.62   

     OD280/OD315 of diluted wines  Proline      Alcohol_cut  
161                          1.82      680   (13.51, 14.75]  
92                           2.06      495   (12.27, 13.51]  
94                           2.96      345  (11.026, 12.27]  
174                          1.56      750   (12.27, 13.51]  
24                           3.82      845   (12.27, 13.51]  
..                            ...      ...              ...  
103                          2.44      415  (11.026, 12.27]  
67                           3.48      510   (12.27, 13.51]  
117                          2.96      345   (12.27, 13.51]  
47                           3.33      985   (13.51, 14.75]  
172                          1.71      660   (13.51, 14.75]  

[142 rows x 14 columns]

## 4. Missing value

- Drop columns
- Deal with NA

In [79]:
## Drop columns
##  df.drop(['c1','c2'],axis = 1)

train_df = train_df_raw.copy()

train_df = train_df.drop(['F1','F4'],axis = 1)
train_df.head()

Class  F2  F3
0    c1   L   1
1    c2   X   3
2    c3  XL   4
3    c4   S   3
4    c2   S   2

### Deal with NA data

- empty and NA column will both converted to NaN
- na is not equal to NaN
- drop rows with NA
- fill NA with value
- 若na直很少  建議直接drop
- drop後 建議reset index 避免缺 index >> dropna().reset_index(drop=True)

### Drop NA

In [110]:

data = pd.read_csv("data/NAdata.csv")
print('original data')
print(data,'\n')

data_drop  = data.dropna(subset = ['A','B','C','D']).reset_index(drop = True)
print(data_drop)

### 2. Drop NA column

data_drop_column = data.dropna(axis =1 )
data_drop_column

#### 3. only drop rows where all columns are NaN

data_drop_all_NA_column = data.dropna(how ='all')
data_drop_all_NA_column

#### 4. drop rows where na appear in specific coulmns

data_drop_c = data.dropna(subset = ['C'])
data_drop_c

### 5. Check how many Na

print('Total NA values')
print(data.isnull().sum().sort_values(ascending =True))


### 6. Check which rows are Na

# Drop E column first

data_ABCD = data.drop(['E'],axis = 1)
## Which row in B is null
data_ABCD[data_ABCD['B'].isnull()]

original data
     A     B     C    D   E
0  1.0  13.0  10.0  5.0 NaN
1  1.0  14.0   9.0  5.0 NaN
2  2.0  16.0   NaN  5.0 NaN
3  2.0  15.0   7.0  5.0 NaN
4  3.0  11.0   6.0  5.0 NaN
5  3.0   NaN   5.0  5.0 NaN
6  4.0  10.0   4.0  5.0 NaN
7  NaN   NaN   NaN  NaN NaN 

     A     B     C    D   E
0  1.0  13.0  10.0  5.0 NaN
1  1.0  14.0   9.0  5.0 NaN
2  2.0  15.0   7.0  5.0 NaN
3  3.0  11.0   6.0  5.0 NaN
4  4.0  10.0   4.0  5.0 NaN
Total NA values
A    1
D    1
B    2
C    2
E    8
dtype: int64


A   B    C    D
5  3.0 NaN  5.0  5.0
7  NaN NaN  NaN  NaN

###  Fill NA

In [112]:
### 6. Fill NaN with some value

data.fillna(0)

#### 7. fill na by columns

values = {'A': 0, 'B': 1, 'C': 2, 'D': 3,'E':4}

data.fillna(value=values)

#### 8. fill na with mean(),max(),min()

data.fillna(data.mean())

## Or

data[['B']] = data[['B']].fillna(np.mean(data[['B']]))
data


#### 9. fillna with mode
data[['C']] = data[['C']].fillna(data['B'].mode()[0])
data

A          B          C    D   E
0  1.0  13.000000  10.000000  5.0 NaN
1  1.0  14.000000   9.000000  5.0 NaN
2  2.0  16.000000  13.166667  5.0 NaN
3  2.0  15.000000   7.000000  5.0 NaN
4  3.0  11.000000   6.000000  5.0 NaN
5  3.0  13.166667   5.000000  5.0 NaN
6  4.0  10.000000   4.000000  5.0 NaN
7  NaN  13.166667  13.166667  NaN NaN

## 5. Correlation analysis
- Correlation plot
- Correlation matrix

In [116]:
corr = x_train.corr()
corr

Alcohol  Malic acid       Ash  \
Alcohol                       1.000000    0.100874  0.266207   
Malic acid                    0.100874    1.000000  0.173466   
Ash                           0.266207    0.173466  1.000000   
Alcalinity of ash            -0.273232    0.266779  0.445968   
Magnesium                     0.235365   -0.031623  0.201369   
Total phenols                 0.314484   -0.322541  0.160595   
Flavanoids                    0.276553   -0.417179  0.093388   
Nonflavanoid phenols         -0.100155    0.330698  0.158221   
Proanthocyanins               0.129632   -0.219270  0.017448   
Color intensity               0.566025    0.302503  0.261122   
Hue                          -0.067541   -0.541480 -0.094603   
OD280/OD315 of diluted wines  0.057073   -0.391111 -0.011545   
Proline                       0.619813   -0.186186  0.190943   

                              Alcalinity of ash  Magnesium  Total phenols  \
Alcohol                               -0.273232   0.235365       0.314484   
Malic acid                             0.266779  -0.031623      -0.322541   
Ash                                    0.445968   0.201369       0.160595   
Alcalinity of ash                      1.000000  -0.100902      -0.325718   
Magnesium                             -0.100902   1.000000       0.182268   
Total phenols                         -0.325718   0.182268       1.000000   
Flavanoids                            -0.399852   0.165807       0.858048   
Nonflavanoid phenols                   0.386218  -0.310549      -0.454415   
Proanthocyanins                       -0.215529   0.260233       0.622975   
Color intensity                        0.012670   0.151305      -0.062106   
Hue                                   -0.252494   0.042404       0.452515   
OD280/OD315 of diluted wines          -0.298203   0.029867       0.709367   
Proline                               -0.432653   0.339024       0.528110   

                              Flavanoids  Nonflavanoid phenols  \
Alcohol                         0.276553             -0.100155   
Malic acid                     -0.417179              0.330698   
Ash                             0.093388              0.158221   
Alcalinity of ash              -0.399852              0.386218   
Magnesium                       0.165807             -0.310549   
Total phenols                   0.858048             -0.454415   
Flavanoids                      1.000000             -0.576292   
Nonflavanoid phenols           -0.576292              1.000000   
Proanthocyanins                 0.662524             -0.323831   
Color intensity                -0.204740              0.192717   
Hue                             0.587220             -0.328522   
OD280/OD315 of diluted wines    0.797165             -0.509848   
Proline                         0.539812             -0.330599   

                              Proanthocyanins  Color intensity       Hue  \
Alcohol                              0.129632         0.566025 -0.067541   
Malic acid                          -0.219270         0.302503 -0.541480   
Ash                                  0.017448         0.261122 -0.094603   
Alcalinity of ash                   -0.215529         0.012670 -0.252494   
Magnesium                            0.260233         0.151305  0.042404   
Total phenols                        0.622975        -0.062106  0.452515   
Flavanoids                           0.662524        -0.204740  0.587220   
Nonflavanoid phenols                -0.323831         0.192717 -0.328522   
Proanthocyanins                      1.000000        -0.031313  0.310292   
Color intensity                     -0.031313         1.000000 -0.545881   
Hue                                  0.310292        -0.545881  1.000000   
OD280/OD315 of diluted wines         0.505636        -0.453062  0.605034   
Proline                              0.352720         0.309687  0.226759   

                              OD280/OD315 of diluted wines   Prol